import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "react-hot-toast";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
        <Toaster
        toastOptions={{
          success: {
            style: {
              backgroundColor: '#4B5563', // Tailwind gray-600
              color: 'white',
            },
          },
          error: {
            style: {
              backgroundColor: '#7C3AED', // Tailwind purple-600
              color: 'white',
            },
          },
        }}
      />

      </body>
    </html>
  );
}
